site_name: Shadow the Hedgehog Speedrunning
site_url: https://shadowspeedrun.com/
theme: slate
repo_url: https://github.com/ShadowSpeedrun/ShadowSpeedrun.github.io
edit_uri: ""
nav:
    - Home: index.md
    - Guides:
        - Health, Points, and Other Values for Routing: ShadowPointsGuide.md